function showSubmissionDetail(idx){_editingIdx=null;const s=_sortedSubs[idx];if(!s)return;document.getElementById("selectedSubmissionDetail").classList.remove("hidden");renderDetailView(s,idx)}
function renderDetailView(s,idx){const calc=s.calcTotal!=null?s.calcTotal:(s.items||[]).reduce((a,i)=>a+(i.income||0),0);const diff=s.diff!=null?s.diff:((s.cashAmount||0)+(s.cardTotal||0)-calc);let html=`<div class="card" style="margin-top:12px"><h3>${s.employeeName} — ${s.date} ${s.locked?"🔒":""}</h3><p>${s.shift||""} ${s.location?"· "+s.location:""}</p><table><thead><tr><th>Бараа</th><th>Өмнөх</th><th>Дараах</th><th>Зарсан</th><th>Орлого</th></tr></thead><tbody>`;(s.items||[]).forEach(it=>{html+=`<tr><td class="product-name">${it.name}</td><td>${it.prev||0}</td><td>${it.next||0}</td><td>${it.sold||0}</td><td>${(it.income||0).toLocaleString()}</td></tr>`});html+=`</tbody></table><p>Бэлэн: ${(s.cashAmount||0).toLocaleString()} · Карт: ${(s.cardTotal||0).toLocaleString()} · Бодсон: ${calc.toLocaleString()} · Зөрүү: <span class="${Math.abs(diff)<0.01?"diff-ok":(diff>0?"diff-over":"diff-short")}">${(diff>=0?"+":"")+diff.toLocaleString()}</span></p><div class="no-print"><button class="btn btn-sm" onclick="startEditSubmission(${idx})">Засах</button> <button class="btn btn-sm btn-warning" onclick="toggleLock(${idx})">${s.locked?"Түгжээ тайлах":"Түгжих"}</button> <button class="btn btn-sm btn-danger" onclick="deleteSubmission(${idx})">Устгах</button></div><div id="editAlert"></div></div>`;document.getElementById("selectedSubmissionDetail").innerHTML=html}
function startEditSubmission(idx){const s=_sortedSubs[idx];if(!s||s.locked){alert("Түгжигдсэн");return}_editingIdx=idx;let html=`<div class="card"><h3>Засах: ${s.employeeName}</h3><div class="header-info"><div><label>Огноо</label><input type="date" id="edit_date" value="${s.date||""}"></div><div><label>Ээлж</label><input id="edit_shift" value="${s.shift||""}"></div><div><label>Шалгагч</label><input id="edit_checker" value="${s.checkerName||""}"></div><div><label>Хүлээн авагч</label><input id="edit_receiver" value="${s.receiverName||""}"></div></div><table><thead><tr><th>Бараа</th><th>Өмнөх</th><th>Дараах</th><th>Зарсан</th><th>Орлого</th></tr></thead><tbody>`;(s.items||[]).forEach((it,i)=>{html+=`<tr><td>${it.name}</td><td><input type="number" id="edit_prev_${i}" value="${it.prev||0}" oninput="editCalc(${i})"></td><td><input type="number" id="edit_next_${i}" value="${it.next||0}" oninput="editCalc(${i})"></td><td><input type="number" id="edit_sold_${i}" value="${it.sold||0}" oninput="editCalcIncome(${i})"></td><td><input type="number" id="edit_income_${i}" value="${it.income||0}"></td></tr>`});html+=`</tbody></table><div class="footer-fields"><div><label>Бэлэн</label><input type="number" id="edit_cash" value="${s.cashAmount||0}"></div><div><label>Карт</label><input type="number" id="edit_card" value="${s.cardTotal||0}"></div><div><label>POS</label><input id="edit_pos" value="${s.posNumber||""}"></div><div><label>Үлдэгдэл</label><input type="number" id="edit_balance" value="${s.cashBalance||0}"></div></div><button class="btn btn-success btn-sm" onclick="saveEditSubmission(${idx})">Хадгалах</button> <button class="btn btn-secondary btn-sm" onclick="cancelEdit()">Болих</button><div id="editAlert"></div></div>`;document.getElementById("selectedSubmissionDetail").innerHTML=html}
function cancelEdit(){_editingIdx=null;const idx=_sortedSubs.findIndex((x,i)=>i===_editingIdx);loadSupervisorData()}
function editCalc(i){const prev=Number(document.getElementById("edit_prev_"+i).value)||0;const next=Number(document.getElementById("edit_next_"+i).value)||0;document.getElementById("edit_sold_"+i).value=Math.max(0,prev-next);editCalcIncome(i)}
function editCalcIncome(i){const sold=Number(document.getElementById("edit_sold_"+i).value)||0;const s=_sortedSubs[_editingIdx];const price=(s.items[i]&&s.items[i].price)||0;document.getElementById("edit_income_"+i).value=sold*price}
async function saveEditSubmission(idx){const s=_sortedSubs[idx];if(!s)return;const oldSold={};s.items.forEach(it=>{oldSold[it.id]=it.sold||0});const items=s.items.map((it,i)=>({...it,prev:Number(document.getElementById("edit_prev_"+i).value)||0,next:Number(document.getElementById("edit_next_"+i).value)||0,sold:Number(document.getElementById("edit_sold_"+i).value)||0,income:Number(document.getElementById("edit_income_"+i).value)||0}));let products=getProducts();items.forEach(it=>{const d=(oldSold[it.id]||0)-(it.sold||0);const pi=products.findIndex(p=>p.id===it.id);if(pi>=0)products[pi].stock=Math.max(0,(products[pi].stock||0)+d)});setProducts(products);const calcTotal=items.reduce((a,i)=>a+(i.income||0),0);const cashAmount=Number(document.getElementById("edit_cash").value)||0;const cardTotal=Number(document.getElementById("edit_card").value)||0;const collected=cashAmount+cardTotal;const updated={...s,date:document.getElementById("edit_date").value||s.date,shift:document.getElementById("edit_shift").value||s.shift,checkerName:document.getElementById("edit_checker").value,receiverName:document.getElementById("edit_receiver").value,items,cashAmount,cardTotal,posNumber:document.getElementById("edit_pos").value,cashBalance:Number(document.getElementById("edit_balance").value)||0,calcTotal,collected,diff:collected-calcTotal,submittedAt:new Date().toISOString(),editedBy:currentUser.id};setSubs(getSubs().map(sub=>(sub.employeeId===s.employeeId&&sub.date===s.date&&(sub.shift||"")===(s.shift||""))?updated:sub));await afterLocalWrite();showAlert("editAlert","Засагдлаа!","success");setTimeout(()=>{loadSupervisorData()},400)}
async function deleteSubmission(idx){const s=_sortedSubs[idx];if(!s)return;if(!confirm(`${s.employeeName} — ${s.date} устгах уу?`))return;let products=getProducts();s.items.forEach(it=>{const pi=products.findIndex(p=>p.id===it.id);if(pi>=0)products[pi].stock=(products[pi].stock||0)+(it.sold||0)});setProducts(products);setSubs(getSubs().filter(sub=>!(sub.employeeId===s.employeeId&&sub.date===s.date&&(sub.shift||"")===(s.shift||""))));await afterLocalWrite();document.getElementById("selectedSubmissionDetail").classList.add("hidden");loadSupervisorData()}
async function toggleLock(idx){const s=_sortedSubs[idx];if(!s)return;const all=getSubs();const i=all.findIndex(sub=>sub.employeeId===s.employeeId&&sub.date===s.date&&(sub.shift||"")===(s.shift||""));if(i>=0){all[i].locked=!all[i].locked;setSubs(all);await afterLocalWrite();loadSupervisorData();const ni=_sortedSubs.findIndex(x=>x.employeeId===s.employeeId&&x.date===s.date);if(ni>=0)showSubmissionDetail(ni)}}
function buildStockTable(){const tbody=document.getElementById("stockBody");if(!tbody)return;tbody.innerHTML="";getProducts().filter(p=>!p.deleted).forEach(p=>{const sc=(p.stock||0)<=LOW_STOCK?"stock-low":"stock-ok";tbody.innerHTML+=`<tr><td>${p.id}</td><td><input id="st_name_${p.id}" value="${p.name}" style="width:120px"></td><td><input type="number" id="st_price_${p.id}" value="${p.price||0}" style="width:80px"></td><td class="${sc}"><input type="number" id="st_stock_${p.id}" value="${p.stock||0}" style="width:70px"></td><td><button class="btn btn-sm" onclick="saveProductRow(${p.id})">Хадгалах</button> <button class="btn btn-sm btn-danger" onclick="deleteProduct(${p.id})">Устгах</button></td></tr>`})}
async function addProduct(){const name=document.getElementById("newProdName").value.trim();const price=Number(document.getElementById("newProdPrice").value)||0;const stock=Number(document.getElementById("newProdStock").value)||0;if(!name){showAlert("stockAlert","Нэр оруулна уу","error");return}const products=getProducts();const id=products.reduce((m,p)=>Math.max(m,p.id||0),0)+1;products.push({id,name,price,stock});setProducts(products);await afterLocalWrite();document.getElementById("newProdName").value="";document.getElementById("newProdPrice").value=0;document.getElementById("newProdStock").value=0;showAlert("stockAlert","Нэмэгдлээ","success");buildStockTable()}
async function saveProductRow(id){const products=getProducts();const i=products.findIndex(p=>p.id===id);if(i<0)return;products[i].name=document.getElementById("st_name_"+id).value.trim()||products[i].name;products[i].price=Number(document.getElementById("st_price_"+id).value)||0;products[i].stock=Number(document.getElementById("st_stock_"+id).value)||0;setProducts(products);await afterLocalWrite();showAlert("stockAlert","Хадгаллаа","success");buildStockTable()}
async function deleteProduct(id){if(!confirm("Устгах уу?"))return;const products=getProducts();const i=products.findIndex(p=>p.id===id);if(i>=0){products[i].deleted=true;setProducts(products);await afterLocalWrite();buildStockTable()}}
function buildPricesTable(){const tbody=document.getElementById("pricesBody");if(!tbody)return;tbody.innerHTML="";getActiveProducts().forEach(p=>{tbody.innerHTML+=`<tr><td>${p.id}</td><td class="product-name">${p.name}</td><td><input type="number" id="price_${p.id}" value="${p.price||0}"></td></tr>`})}
async function savePrices(){const products=getProducts();getActiveProducts().forEach(p=>{const el=document.getElementById("price_"+p.id);if(el){const i=products.findIndex(x=>x.id===p.id);if(i>=0)products[i].price=Number(el.value)||0}});setProducts(products);await afterLocalWrite();showAlert("priceAlert","Үнэ хадгалагдлаа","success");buildPricesTable()}
function buildUsersTable(){const tbody=document.getElementById("usersBody");if(!tbody)return;const users=getUsers();tbody.innerHTML="";Object.keys(users).forEach(id=>{const u=users[id];tbody.innerHTML+=`<tr><td>${id}</td><td><input id="usr_name_${id}" value="${u.name}"></td><td><select id="usr_role_${id}"><option value="employee" ${u.role==="employee"?"selected":""}>Ажилтан</option><option value="supervisor" ${u.role==="supervisor"?"selected":""}>Ахлах</option></select></td><td><input id="usr_pin_${id}" value="${u.pin||""}" placeholder="PIN" style="width:70px"></td><td><button class="btn btn-sm" onclick="saveUserRow('${id}')">Хадгалах</button> <button class="btn btn-sm btn-danger" onclick="deleteUser('${id}')">Устгах</button></td></tr>`})}
async function addUser(){const id=(document.getElementById("newUserId").value||"").trim().toLowerCase();const name=(document.getElementById("newUserName").value||"").trim();const role=document.getElementById("newUserRole").value;if(!id||!name){showAlert("userAlert","ID болон нэр","error");return}const users=getUsers();if(users[id]){showAlert("userAlert","ID давхцаж байна","error");return}users[id]={name,role,pin:""};setUsers(users);await afterLocalWrite();document.getElementById("newUserId").value="";document.getElementById("newUserName").value="";showAlert("userAlert","Нэмэгдлээ","success");buildUsersTable();updateLoginHint()}
async function saveUserRow(id){const name=document.getElementById("usr_name_"+id).value.trim();const role=document.getElementById("usr_role_"+id).value;const pin=document.getElementById("usr_pin_"+id).value.trim();if(!name){showAlert("userAlert","Нэр хоосон","error");return}const users=getUsers();if(!users[id])return;users[id]={name,role,pin};setUsers(users);await afterLocalWrite();showAlert("userAlert","Хадгаллаа","success");buildUsersTable();updateLoginHint()}
async function deleteUser(id){if(currentUser&&currentUser.id===id){showAlert("userAlert","Өөрийгөө устгах боломжгүй","error");return}const users=getUsers();if(!users[id])return;if(users[id].role==="supervisor"){const otherSup=Object.keys(users).filter(k=>k!==id&&users[k].role==="supervisor");if(!otherSup.length){showAlert("userAlert","Сүүлийн ахлалыг устгах боломжгүй","error");return}}if(!confirm(`«${id}» устгах уу?`))return;delete users[id];setUsers(users);await afterLocalWrite();showAlert("userAlert","Устгагдлаа","success");buildUsersTable();updateLoginHint()}
function fillSyncForm(){}
async function saveSyncSettings(){}
async function manualPull(){await cloudPull();if(currentUser&&currentUser.role==="supervisor")loadSupervisorData()}
async function manualPush(){await cloudPush()}
function clearSyncSettings(){}
function exportData(){const blob=new Blob([JSON.stringify(packAll(),null,2)],{type:"application/json"});const a=document.createElement("a");a.href=URL.createObjectURL(blob);a.download="borluulalt_backup.json";a.click()}
async function importData(ev){const file=ev.target.files[0];if(!file)return;const reader=new FileReader();reader.onload=async()=>{try{const data=JSON.parse(reader.result);applyAll(data);await afterLocalWrite();if(currentUser&&currentUser.role==="supervisor")loadSupervisorData();updateLoginHint();alert("Импорт амжилттай! ☁️ Firebase рүү илгээлээ.")}catch(e){alert("Алдаа: "+e.message)}};reader.readAsText(file);ev.target.value=""}
