function fillSyncForm(){}
async function saveSyncSettings(){}
async function manualPull(){await cloudPull();if(typeof loadSupervisorData==="function")loadSupervisorData()}
async function manualPush(){await cloudPush()}
function clearSyncSettings(){}
function initReportFilters(){const emps=document.getElementById("reportEmp");if(!emps)return;const users=getUsers();emps.innerHTML="<option value=\"\">Бүгд</option>"+Object.keys(users).filter(id=>users[id].role==="employee").map(id=>`<option value=\"${id}\">${users[id].name}</option>`).join("");const locs=document.getElementById("reportLoc");if(locs){const set=new Set(getSubs().map(s=>s.location).filter(Boolean));locs.innerHTML="<option value=\"\">Бүгд</option>"+[...set].map(l=>`<option value=\"${l}\">${l}</option>`).join("")}}
function runReport(){const from=document.getElementById("reportFrom").value;const to=document.getElementById("reportTo").value;const emp=document.getElementById("reportEmp").value;const loc=(document.getElementById("reportLoc")||{}).value||"";let rows=getSubs().slice();if(from)rows=rows.filter(s=>s.date>=from);if(to)rows=rows.filter(s=>s.date<=to);if(emp)rows=rows.filter(s=>s.employeeId===emp);if(loc)rows=rows.filter(s=>s.location===loc);_reportRows=rows;let totalSold=0,totalIncome=0,totalDiff=0;rows.forEach(s=>{s.items.forEach(it=>{totalSold+=it.sold||0;totalIncome+=it.income||0});totalDiff+=(s.diff!=null?s.diff:0)});const box=document.getElementById("reportSummary");if(box)box.innerHTML=`<div class=\"summary-item\"><div class=\"label\">Илгээлт</div><div class=\"value\">${rows.length}</div></div><div class=\"summary-item\"><div class=\"label\">Борлуулсан</div><div class=\"value\">${totalSold}</div></div><div class=\"summary-item\"><div class=\"label\">Орлого</div><div class=\"value\">${totalIncome.toLocaleString()}₮</div></div><div class=\"summary-item\"><div class=\"label\">Зөрүү</div><div class=\"value\">${(totalDiff>=0?\"+\":\"\")+totalDiff.toLocaleString()}</div></div>`;const tbody=document.getElementById("reportBody");if(!tbody)return;tbody.innerHTML=rows.map(s=>{const calc=s.calcTotal!=null?s.calcTotal:(s.items||[]).reduce((a,i)=>a+(i.income||0),0);const diff=s.diff!=null?s.diff:((s.cashAmount||0)+(s.cardTotal||0)-calc);return `<tr><td>${s.date}</td><td>${s.employeeName}</td><td>${s.shift||\"—\"}</td><td>${s.location||\"—\"}</td><td>${calc.toLocaleString()}</td><td class=\"${Math.abs(diff)<0.01?\"diff-ok\":(diff>0?\"diff-over\":\"diff-short\")}\">${(diff>=0?\"+\":\"\")+diff.toLocaleString()}</td></tr>`}).join("")||"<tr><td colspan=6>Хоосон</td></tr>"}
function buildLogTable(){const logs=getLogs().slice().reverse();const tbody=document.getElementById("logBody");if(!tbody)return;tbody.innerHTML=logs.map(l=>`<tr><td>${new Date(l.at).toLocaleString(\"mn-MN\")}</td><td>${l.user}</td><td>${l.action}</td><td>${l.detail||\"\"}</td></tr>`).join("")||"<tr><td colspan=4>Хоосон</td></tr>"}
function exportCSV(){const rows=_reportRows.length?_reportRows:getSubs();let csv=\"Огноо,Ажилтан,Ээлж,Байршил,Орлого,Зөрүү\\n\";rows.forEach(s=>{const calc=s.calcTotal!=null?s.calcTotal:(s.items||[]).reduce((a,i)=>a+(i.income||0),0);const diff=s.diff!=null?s.diff:((s.cashAmount||0)+(s.cardTotal||0)-calc);csv+=`${s.date},${s.employeeName},${s.shift||\"\"},${s.location||\"\"},${calc},${diff}\\n`});const blob=new Blob([\"\\uFEFF\"+csv],{type:\"text/csv;charset=utf-8;\"});const a=document.createElement(\"a\");a.href=URL.createObjectURL(blob);a.download=\"borluulalt_report.csv\";a.click()}
function exportData(){const blob=new Blob([JSON.stringify(packAll(),null,2)],{type:\"application/json\"});const a=document.createElement(\"a\");a.href=URL.createObjectURL(blob);a.download=\"borluulalt_backup.json\";a.click()}
function printReport(){window.print()}
async function importData(ev){const file=ev.target.files[0];if(!file)return;const reader=new FileReader();reader.onload=async()=>{try{const data=JSON.parse(reader.result);applyAll(data);await afterLocalWrite();if(currentUser&&currentUser.role===\"supervisor\")loadSupervisorData();updateLoginHint();alert(\"Импорт амжилттай! ☁️ Firebase рүү илгээлээ.\")}catch(e){alert(\"Алдаа: \"+e.message)}};reader.readAsText(file);ev.target.value=\"\"}
